# Generated by Django 5.0.6 on 2024-06-02 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_employee'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Members',
            new_name='Member',
        ),
    ]
